/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.sun.awt.AWTUtilities;
import java.awt.Frame;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author Z4ND3R
 */
public class vistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form vistaMenu
     */
    public vistaMenu() {
        initComponents();
        setLocationRelativeTo(this);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 20, 20);
        AWTUtilities.setWindowShape(this, forma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPermutaciones = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnTeoriaConjuntos = new javax.swing.JButton();
        btnCombinaciones = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnPermutaciones1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        btnTFA = new javax.swing.JButton();
        btnCongruencia = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(243, 235, 212));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPermutaciones.setBackground(new java.awt.Color(243, 235, 212));
        btnPermutaciones.setForeground(new java.awt.Color(51, 51, 51));
        btnPermutaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargo.png"))); // NOI18N
        btnPermutaciones.setText("Permutaciones");
        btnPermutaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPermutaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPermutaciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargoPressed.png"))); // NOI18N
        btnPermutaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermutacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnPermutaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 210, 35));

        jButton5.setBackground(new java.awt.Color(243, 235, 212));
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargo.png"))); // NOI18N
        jButton5.setText("MCD");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargoPressed.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 210, 35));

        btnTeoriaConjuntos.setBackground(new java.awt.Color(243, 235, 212));
        btnTeoriaConjuntos.setForeground(new java.awt.Color(51, 51, 51));
        btnTeoriaConjuntos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargo.png"))); // NOI18N
        btnTeoriaConjuntos.setText("Teoría de Conjuntos");
        btnTeoriaConjuntos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTeoriaConjuntos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTeoriaConjuntos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargoPressed.png"))); // NOI18N
        btnTeoriaConjuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeoriaConjuntosActionPerformed(evt);
            }
        });
        jPanel1.add(btnTeoriaConjuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 210, 35));

        btnCombinaciones.setBackground(new java.awt.Color(243, 235, 212));
        btnCombinaciones.setForeground(new java.awt.Color(51, 51, 51));
        btnCombinaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargo.png"))); // NOI18N
        btnCombinaciones.setText("Combinaciones");
        btnCombinaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCombinaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCombinaciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargoPressed.png"))); // NOI18N
        btnCombinaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombinacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnCombinaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 210, 35));

        jButton1.setBackground(new java.awt.Color(243, 235, 212));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVolverDos.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVolverPressedDos.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 30, 30));

        btnPermutaciones1.setBackground(new java.awt.Color(243, 235, 212));
        btnPermutaciones1.setForeground(new java.awt.Color(51, 51, 51));
        btnPermutaciones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargo.png"))); // NOI18N
        btnPermutaciones1.setText("Disposiciones Lineales");
        btnPermutaciones1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPermutaciones1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPermutaciones1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargoPressed.png"))); // NOI18N
        btnPermutaciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermutaciones1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPermutaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 210, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jButton8.setBackground(new java.awt.Color(243, 235, 212));
        jButton8.setForeground(new java.awt.Color(51, 51, 51));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargo.png"))); // NOI18N
        jButton8.setText("Relaciones y funciones");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargoPressed.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 210, 35));

        btnTFA.setBackground(new java.awt.Color(243, 235, 212));
        btnTFA.setForeground(new java.awt.Color(51, 51, 51));
        btnTFA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargo.png"))); // NOI18N
        btnTFA.setText("Teorema Fundamental Aritmética");
        btnTFA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTFA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTFA.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargoPressed.png"))); // NOI18N
        btnTFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTFAActionPerformed(evt);
            }
        });
        jPanel1.add(btnTFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 210, 35));

        btnCongruencia.setBackground(new java.awt.Color(243, 235, 212));
        btnCongruencia.setForeground(new java.awt.Color(51, 51, 51));
        btnCongruencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargo.png"))); // NOI18N
        btnCongruencia.setText("Congruencia");
        btnCongruencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCongruencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCongruencia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLargoPressed.png"))); // NOI18N
        btnCongruencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongruenciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCongruencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 210, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 350, 520));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnMinimizar.png"))); // NOI18N
        jButton3.setToolTipText("Minimizar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnMinimizar_Click.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCerrar.png"))); // NOI18N
        jButton2.setToolTipText("Cerrar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCerrar_Click.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(298, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MCDView view = new MCDView();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnTeoriaConjuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeoriaConjuntosActionPerformed
        vistaTeoriaConjuntos vistaConjuntos = new vistaTeoriaConjuntos();
        vistaConjuntos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTeoriaConjuntosActionPerformed

    private void btnCombinacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombinacionesActionPerformed
        ComView comview = new ComView();
        comview.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCombinacionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        vistaHome vistaH = new vistaHome();
        vistaH.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPermutacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermutacionesActionPerformed
        PermView view = new PermView();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPermutacionesActionPerformed

    private void btnPermutaciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermutaciones1ActionPerformed
        DispLinView view = new DispLinView();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPermutaciones1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        VistaRelacionesFunciones vistaRF = new VistaRelacionesFunciones();
        vistaRF.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnTFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTFAActionPerformed
        VistaTFA vistaTFA = new VistaTFA();
        vistaTFA.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTFAActionPerformed

    private void btnCongruenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongruenciaActionPerformed
        CongView congView = new CongView();
        congView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCongruenciaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(vistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(vistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(vistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(vistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new vistaMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCombinaciones;
    private javax.swing.JButton btnCongruencia;
    private javax.swing.JButton btnPermutaciones;
    private javax.swing.JButton btnPermutaciones1;
    private javax.swing.JButton btnTFA;
    private javax.swing.JButton btnTeoriaConjuntos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
